import { defaultCost } from "./governance";
import type {
  Attraction,
  Booking,
  PackingItem,
  TripTask,
  DecisionSettings,
  KintripState,
  Suggestion,
  SuggestionStatus,
  Traveller,
  TravellerConstraint,
  TripRole,
  VoteValue,
} from "./types";

const pref = (
  interests: string[],
  pace: Traveller["preferences"]["pace"],
  walking: Traveller["preferences"]["walking"],
  mustDo: string,
  constraints: string,
) => ({ interests, pace, walking, mustDo, avoid: "", constraints });

const rawTravellers: Omit<Traveller, "roles" | "needs">[] = [
  {
    id: "dad",
    name: "Wei (Dad)",
    relationship: "Organiser",
    ageGroup: "adult",
    role: "organiser",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Culture", "Food", "Sightseeing"],
      "balanced",
      "moderate",
      "Senso-ji, Tsukiji Outer Market",
      "Wants efficient routing between stops",
    ),
  },
  {
    id: "mum",
    name: "Lin (Mum)",
    relationship: "Parent",
    ageGroup: "adult",
    role: "member",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Shopping", "Food", "Nature"],
      "relaxed",
      "moderate",
      "Shibuya, Nishiki Market",
      "Would like proper shopping time",
    ),
  },
  {
    id: "grandpa",
    name: "Grandpa Tan, 73",
    relationship: "Grandparent",
    ageGroup: "senior",
    role: "member",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Culture", "Temples", "Food"],
      "relaxed",
      "low",
      "Senso-ji, Fushimi Inari",
      "Needs regular rests; avoid steep or long walks",
    ),
  },
  {
    id: "grandma",
    name: "Grandma Tan, 70",
    relationship: "Grandparent",
    ageGroup: "senior",
    role: "member",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Nature", "Food", "Sightseeing"],
      "relaxed",
      "low",
      "Gardens, Nishiki Market",
      "Rest after lunch preferred",
    ),
  },
  {
    id: "son",
    name: "Jayden, 17",
    relationship: "Son",
    ageGroup: "teen",
    role: "member",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Anime", "Technology", "Food"],
      "packed",
      "high",
      "Akihabara, teamLab Planets",
      "Happy with long days",
    ),
  },
  {
    id: "daughter",
    name: "Maya, 12",
    relationship: "Daughter",
    ageGroup: "child",
    role: "member",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Theme parks", "Animals", "Shopping"],
      "balanced",
      "moderate",
      "teamLab Planets",
      "Gets tired on very long days",
    ),
  },
  {
    id: "aunt",
    name: "Aunty Serene, 43",
    relationship: "Aunt",
    ageGroup: "adult",
    role: "member",
    joined: true,
    prefStatus: "complete",
    preferences: pref(
      ["Culture", "Photography", "Food"],
      "balanced",
      "high",
      "Fushimi Inari, Arashiyama",
      "Early starts are fine",
    ),
  },
];

const need = (
  id: string,
  type: TravellerConstraint["type"],
  severity: TravellerConstraint["severity"],
  label: string,
  visibility: TravellerConstraint["visibility"] = "group",
): TravellerConstraint => ({ id, type, severity, label, visibility });

const seedRoles: Record<string, TripRole[]> = {
  dad: ["owner", "organiser"],
  mum: ["organiser"],
  aunt: ["sponsor", "contributor"],
  grandpa: ["contributor"],
  grandma: ["contributor"],
  son: ["contributor"],
  daughter: ["viewer"],
};

const seedNeeds: Record<string, TravellerConstraint[]> = {
  grandpa: [need("g1", "max_walk", "hard_limit", "No more than 30 minutes of walking at a time")],
  grandma: [need("g2", "rest_window", "comfort_need", "Needs a sit-down rest each afternoon")],
  daughter: [need("d1", "accompaniment", "comfort_need", "Should stay with an adult", "organisers")],
};

export const seedTravellers: Traveller[] = [
  ...rawTravellers.map((t) => ({
    ...t,
    roles: seedRoles[t.id] ?? (["contributor"] as TripRole[]),
    needs: seedNeeds[t.id] ?? [],
    managed: t.id === "daughter",
    responsibleAdultId: t.id === "daughter" ? "mum" : undefined,
    managementMode: (t.id === "daughter" ? "assisted" : "self") as "assisted" | "self",
    assistAccepted: t.id === "daughter" ? true : undefined,
    canVote: true,
    consentLog: [],
  })),
  // A toddler with care needs but no vote — counted for needs, not for tallies.
  {
    id: "toddler",
    name: "Ethan, 3",
    relationship: "Nephew",
    ageGroup: "child",
    role: "member" as const,
    roles: ["viewer"] as TripRole[],
    managed: true,
    responsibleAdultId: "aunt",
    managementMode: "assisted" as const,
    assistAccepted: true,
    canVote: false,
    consentLog: [
      { at: "2026-12-01T09:00:00.000Z", action: "responsibility_confirmed" as const, by: "Aunty Serene, 43" },
    ],
    needs: [
      need("t1", "rest_window", "hard_limit", "Nap between 13:00 and 15:00", "organisers"),
      need("t2", "step_free", "comfort_need", "Stroller-friendly routes"),
    ],
    joined: true,
    prefStatus: "complete" as const,
    preferences: pref(["Parks", "Animals"], "relaxed", "low", "Somewhere to run around", "Short days"),
  },
];

export const seedAttractions: Attraction[] = [
  {
    id: "sensoji",
    name: "Senso-ji",
    city: "Tokyo",
    area: "Asakusa",
    category: "Culture",
    description: "Tokyo's oldest temple, with a lively market street leading to the main hall.",
    durationMin: 90,
    walking: "moderate",
    cost: "Free",
    indoor: false,
    opens: "06:00",
    closes: "17:00",
    sourceUrl: "https://www.senso-ji.jp/",
  },
  {
    id: "skytree",
    name: "Tokyo Skytree",
    city: "Tokyo",
    area: "Asakusa",
    category: "Sightseeing",
    description: "Observation decks with wide city views, plus shops and cafes indoors.",
    durationMin: 90,
    walking: "low",
    cost: "$$",
    indoor: true,
    opens: "10:00",
    closes: "21:00",
    sourceUrl: "https://www.tokyo-skytree.jp/en/",
  },
  {
    id: "akihabara",
    name: "Akihabara",
    city: "Tokyo",
    area: "Central Tokyo",
    category: "Technology",
    description: "Anime, games and electronics district packed with multi-floor stores.",
    durationMin: 120,
    walking: "moderate",
    cost: "$",
    indoor: true,
    opens: "10:00",
    closes: "20:00",
    sourceUrl: "https://www.gotokyo.org/en/spot/32/",
  },
  {
    id: "shibuya",
    name: "Shibuya",
    city: "Tokyo",
    area: "West Tokyo",
    category: "Shopping",
    description: "The famous crossing, department stores and plenty of places to eat.",
    durationMin: 120,
    walking: "moderate",
    cost: "$",
    indoor: false,
    opens: "10:00",
    closes: "21:00",
    sourceUrl: "https://www.gotokyo.org/en/spot/23/",
  },
  {
    id: "meiji",
    name: "Meiji Shrine",
    city: "Tokyo",
    area: "West Tokyo",
    category: "Culture",
    description: "Calm forest shrine with broad, flat gravel paths.",
    durationMin: 75,
    walking: "moderate",
    cost: "Free",
    indoor: false,
    opens: "05:00",
    closes: "18:00",
    sourceUrl: "https://www.meijijingu.or.jp/en/",
  },
  {
    id: "teamlab",
    name: "teamLab Planets",
    city: "Tokyo",
    area: "Bayside",
    category: "Experience",
    description: "Walk-through digital art rooms. Indoor, seated rest areas nearby.",
    durationMin: 120,
    walking: "moderate",
    cost: "$$",
    indoor: true,
    opens: "09:00",
    closes: "21:00",
    sourceUrl: "https://www.teamlab.art/e/planets/",
  },
  {
    id: "tsukiji",
    name: "Tsukiji Outer Market",
    city: "Tokyo",
    area: "Central Tokyo",
    category: "Food",
    description: "Street food stalls and seafood counters, best in the morning.",
    durationMin: 90,
    walking: "moderate",
    cost: "$",
    indoor: false,
    opens: "07:00",
    closes: "14:00",
    sourceUrl: "https://www.tsukiji.or.jp/english/",
  },
  {
    id: "imperial",
    name: "Imperial Palace East Gardens",
    city: "Tokyo",
    area: "Central Tokyo",
    category: "Nature",
    description: "Open gardens with benches, shade and gentle paths.",
    durationMin: 75,
    walking: "moderate",
    cost: "Free",
    indoor: false,
    opens: "09:00",
    closes: "16:30",
    sourceUrl: "https://www.kunaicho.go.jp/e-event/higashigyoen02.html",
  },
  {
    id: "ginza",
    name: "Ginza shopping district",
    city: "Tokyo",
    area: "Central Tokyo",
    category: "Shopping",
    description: "Department stores and covered walkways, easy to pace indoors.",
    durationMin: 120,
    walking: "low",
    cost: "$$",
    indoor: true,
    opens: "11:00",
    closes: "20:00",
    sourceUrl: "https://www.gotokyo.org/en/spot/45/",
  },
  {
    id: "fushimi",
    name: "Fushimi Inari",
    city: "Kyoto",
    area: "South Kyoto",
    category: "Culture",
    description: "Thousands of torii gates. The lower loop is short; the summit is a long climb.",
    durationMin: 150,
    walking: "high",
    cost: "Free",
    indoor: false,
    opens: "00:00",
    closes: "23:59",
    sourceUrl: "https://inari.jp/en/",
  },
  {
    id: "kiyomizu",
    name: "Kiyomizu-dera",
    city: "Kyoto",
    area: "Higashiyama",
    category: "Culture",
    description: "Hillside temple with a wooden terrace. Approach streets are sloped.",
    durationMin: 105,
    walking: "high",
    cost: "$",
    indoor: false,
    opens: "06:00",
    closes: "18:00",
    sourceUrl: "https://www.kiyomizudera.or.jp/en/",
  },
  {
    id: "gion",
    name: "Gion",
    city: "Kyoto",
    area: "Higashiyama",
    category: "Culture",
    description: "Historic lanes, tea houses and easy flat strolling.",
    durationMin: 75,
    walking: "moderate",
    cost: "Free",
    indoor: false,
    opens: "09:00",
    closes: "21:00",
    sourceUrl: "https://kyoto.travel/en/",
  },
  {
    id: "nishiki",
    name: "Nishiki Market",
    city: "Kyoto",
    area: "Central Kyoto",
    category: "Food",
    description: "Covered market lane of food stalls — sheltered whatever the weather.",
    durationMin: 90,
    walking: "low",
    cost: "$",
    indoor: true,
    opens: "09:30",
    closes: "18:00",
    sourceUrl: "https://www.kyoto-nishiki.or.jp/",
  },
  {
    id: "arashiyama",
    name: "Arashiyama",
    city: "Kyoto",
    area: "West Kyoto",
    category: "Nature",
    description: "Bamboo grove, riverside views and a flat main path.",
    durationMin: 150,
    walking: "moderate",
    cost: "Free",
    indoor: false,
    opens: "08:00",
    closes: "17:30",
    sourceUrl: "https://kyoto.travel/en/",
  },
  {
    id: "kinkakuji",
    name: "Kinkaku-ji",
    city: "Kyoto",
    area: "North Kyoto",
    category: "Culture",
    description: "The Golden Pavilion, seen from a short one-way garden loop.",
    durationMin: 60,
    walking: "low",
    cost: "$",
    indoor: false,
    opens: "09:00",
    closes: "17:00",
    sourceUrl: "https://www.shokoku-ji.jp/en/kinkakuji/",
  },
];

const V = (
  dad: VoteValue,
  mum: VoteValue,
  grandpa: VoteValue,
  grandma: VoteValue,
  son: VoteValue,
  daughter: VoteValue,
  aunt: VoteValue,
) => ({ dad, mum, grandpa, grandma, son, daughter, aunt });

const byAttraction: Record<string, Record<string, VoteValue>> = {
  sensoji: V("MUST_GO", "WOULD_LIKE", "MUST_GO", "MUST_GO", "DONT_MIND", "WOULD_LIKE", "MUST_GO"),
  akihabara: V("DONT_MIND", "SKIP", "SKIP", "SKIP", "MUST_GO", "WOULD_LIKE", "DONT_MIND"),
  teamlab: V("WOULD_LIKE", "WOULD_LIKE", "DONT_MIND", "DONT_MIND", "MUST_GO", "MUST_GO", "WOULD_LIKE"),
  tsukiji: V("MUST_GO", "MUST_GO", "MUST_GO", "MUST_GO", "WOULD_LIKE", "DONT_MIND", "MUST_GO"),
  shibuya: V("WOULD_LIKE", "MUST_GO", "SKIP", "SKIP", "MUST_GO", "MUST_GO", "WOULD_LIKE"),
  fushimi: V("MUST_GO", "WOULD_LIKE", "MUST_GO", "WOULD_LIKE", "WOULD_LIKE", "WOULD_LIKE", "MUST_GO"),
  nishiki: V("MUST_GO", "MUST_GO", "MUST_GO", "MUST_GO", "WOULD_LIKE", "WOULD_LIKE", "MUST_GO"),
  arashiyama: V("WOULD_LIKE", "MUST_GO", "WOULD_LIKE", "MUST_GO", "DONT_MIND", "WOULD_LIKE", "MUST_GO"),
  skytree: V("WOULD_LIKE", "WOULD_LIKE", "DONT_MIND", "WOULD_LIKE", "WOULD_LIKE", "MUST_GO", "DONT_MIND"),
  meiji: V("WOULD_LIKE", "DONT_MIND", "MUST_GO", "WOULD_LIKE", "DONT_MIND", "DONT_MIND", "WOULD_LIKE"),
  imperial: V("WOULD_LIKE", "WOULD_LIKE", "WOULD_LIKE", "MUST_GO", "SKIP", "DONT_MIND", "WOULD_LIKE"),
  ginza: V("DONT_MIND", "MUST_GO", "DONT_MIND", "WOULD_LIKE", "DONT_MIND", "WOULD_LIKE", "DONT_MIND"),
  kiyomizu: V("MUST_GO", "WOULD_LIKE", "WOULD_LIKE", "DONT_MIND", "WOULD_LIKE", "WOULD_LIKE", "MUST_GO"),
  kinkakuji: V("WOULD_LIKE", "WOULD_LIKE", "MUST_GO", "MUST_GO", "DONT_MIND", "WOULD_LIKE", "WOULD_LIKE"),
  gion: V("WOULD_LIKE", "MUST_GO", "WOULD_LIKE", "WOULD_LIKE", "DONT_MIND", "DONT_MIND", "MUST_GO"),
};

function buildVotes() {
  const votes: Record<string, Record<string, VoteValue>> = {};
  for (const t of seedTravellers) votes[t.id] = {};
  for (const [attractionId, row] of Object.entries(byAttraction)) {
    for (const [travellerId, value] of Object.entries(row)) {
      votes[travellerId]![attractionId] = value;
    }
  }
  return votes;
}

const defaultDecisions: DecisionSettings = {
  mode: "organiser",
  voteThreshold: 0.6,
  quorum: 0.5,
  organiserOverrideAllowed: true,
  sponsorThreshold: 100,
  currency: "SGD",
  publication: "organisers",
};

const seedStatuses: Record<string, SuggestionStatus> = {
  sensoji: "approved",
  teamlab: "booked",
  meiji: "approved",
  tsukiji: "approved",
  fushimi: "approved",
  kiyomizu: "approved",
  gion: "approved",
  arashiyama: "approved",
  nishiki: "approved",
  kinkakuji: "approved",
  skytree: "sponsor_approval_required",
  shibuya: "suggested",
  imperial: "suggested",
  ginza: "backup",
  akihabara: "under_review",
};

function buildSuggestions(): Record<string, Suggestion> {
  const out: Record<string, Suggestion> = {};
  for (const a of seedAttractions) {
    const status = seedStatuses[a.id] ?? "suggested";
    const cost = defaultCost(a);
    if (a.id === "skytree") {
      cost.perPerson = 35;
      cost.funding = "shared";
      cost.estimateType = "estimated";
    }
    if (a.id === "teamlab") {
      cost.perPerson = 30;
      cost.funding = "already_booked";
      cost.estimateType = "exact";
    }
    out[a.id] = {
      attractionId: a.id,
      status,
      cost,
      backupTags: a.id === "ginza" ? ["rain", "tired"] : [],
      suggestedBy: "dad",
      history: [],
    };
  }
  return out;
}

const TZ = "Asia/Tokyo";

export const seedBookings: Booking[] = [
  {
    id: "bk-stay",
    type: "stay",
    title: "Hotel Niwa Tokyo",
    provider: "Booked direct",
    status: "confirmed",
    startLocal: "2027-03-20T15:00",
    endLocal: "2027-03-24T11:00",
    timeZone: TZ,
    travellerIds: ["dad", "mum", "grandpa", "grandma", "son", "daughter", "aunt", "toddler"],
    location: "Kanda, Tokyo",
    addressLocal: "\u6771\u4eac\u90fd\u5343\u4ee3\u7530\u533a\u4e09\u5d0e\u753a2-1-16",
    addressTranslated: "2-1-16 Misakicho, Chiyoda City, Tokyo",
    contact: "+81 3 3293 0028",
    ownerId: "dad",
    reference: "NIWA-77413",
    referenceSharedWith: ["mum"],
    createdAt: "2026-12-02T08:00:00.000Z",
    version: 1,
  },
  {
    id: "bk-teamlab",
    type: "activity",
    title: "teamLab Planets entry",
    provider: "Official site",
    status: "confirmed",
    startLocal: "2027-03-22T10:30",
    endLocal: "2027-03-22T12:30",
    timeZone: TZ,
    travellerIds: ["dad", "mum", "son", "daughter", "aunt"],
    location: "Toyosu, Tokyo",
    ownerId: "dad",
    reference: "TLP-2298311",
    referenceSharedWith: [],
    attractionId: "teamlab",
    cancellationDeadline: "2027-03-15",
    createdAt: "2026-12-04T08:00:00.000Z",
    version: 1,
  },
];

export const seedTasks: TripTask[] = [
  {
    id: "tk-rail",
    title: "Buy the rail passes",
    detail: "Seven passes, collect at the airport counter.",
    assigneeId: "dad",
    helperIds: [],
    deadline: "2027-03-01",
    timeZone: TZ,
    state: "accepted",
    visibility: "group",
    version: 1,
    history: [{ at: "2026-12-05T02:00:00.000Z", actorName: "Wei (Dad)", action: "Created" }],
  },
  {
    id: "tk-wheelchair",
    title: "Check step-free routes for Grandpa",
    assigneeId: "mum",
    helperIds: ["aunt"],
    deadline: "2027-03-10",
    timeZone: TZ,
    state: "awaiting_acceptance",
    visibility: "group",
    version: 1,
    history: [{ at: "2026-12-05T02:05:00.000Z", actorName: "Wei (Dad)", action: "Assigned" }],
  },
  {
    id: "tk-snacks",
    title: "Pack snacks for travel days",
    helperIds: [],
    state: "unassigned",
    visibility: "group",
    version: 1,
    history: [{ at: "2026-12-05T02:10:00.000Z", actorName: "Lin (Mum)", action: "Created" }],
  },
];

export const seedPacking: PackingItem[] = [
  {
    id: "pk-stroller",
    label: "Lightweight stroller",
    scope: "shared",
    responsibleId: "aunt",
    quantityNeeded: 1,
    quantityCommitted: 1,
    quantityPacked: 0,
    packed: false,
    visibility: "group",
    version: 1,
  },
  {
    id: "pk-firstaid",
    label: "First aid kit",
    scope: "shared",
    quantityNeeded: 1,
    quantityCommitted: 0,
    quantityPacked: 0,
    packed: false,
    visibility: "group",
    version: 1,
  },
  {
    id: "pk-stick",
    label: "Folding walking stick",
    scope: "dependent",
    travellerId: "grandpa",
    responsibleId: "dad",
    packed: false,
    visibility: "organisers",
    version: 1,
  },
  {
    id: "pk-docs",
    label: "Passport and travel documents",
    scope: "personal",
    travellerId: "dad",
    packed: true,
    visibility: "private",
    version: 1,
  },
];

export function createEmptyTripState(input: {
  title: string;
  destination: string;
  startDate: string;
  endDate: string;
  travellerCount: number;
}): KintripState {
  const id = `trip-${Date.now().toString(36)}`;
  return {
    trip: {
      id,
      title: input.title || "Our family trip",
      destination: input.destination,
      startDate: input.startDate,
      endDate: input.endDate,
      travellerCount: input.travellerCount,
      organiserId: "organiser",
      status: "planning",
    },
    travellers: [
      {
        id: "organiser",
        name: "You (Organiser)",
        relationship: "Organiser",
        ageGroup: "adult",
        role: "organiser",
        roles: ["owner", "organiser"],
        needs: [],
        joined: true,
        prefStatus: "not_started",
        preferences: {
          interests: [],
          pace: "balanced",
          walking: "moderate",
          mustDo: "",
          avoid: "",
          constraints: "",
        },
      },
    ],
    // New trips start empty — the family builds the shortlist from Google Maps search.
    attractions: [],
    votes: {},
    suggestions: {},
    decisions: { ...defaultDecisions },
    sponsorApprovals: [],
    notifications: [],
    audit: [],
    itinerary: null,
    notes: [],
    bookings: [],
    tasks: [],
    packing: [],
    activeTravellerId: "organiser",
    currentDay: 1,
    replanLog: [],
    cachedAt: null,
  };
}

export function createSeedState(): KintripState {
  return {
    trip: {
      id: "tan-japan-2027",
      title: "Tan Family Japan 2027",
      destination: "Tokyo + Kyoto, Japan",
      startDate: "2027-03-20",
      endDate: "2027-03-27",
      travellerCount: 7,
      organiserId: "dad",
      status: "planning",
    },
    travellers: seedTravellers,
    attractions: seedAttractions,
    votes: buildVotes(),
    suggestions: buildSuggestions(),
    decisions: { ...defaultDecisions, sharedBudget: 4000 },
    sponsorApprovals: [],
    notifications: [],
    audit: [],
    itinerary: null,
    notes: [
      { id: "n1", scope: "trip", text: "Tickets and rail passes are with Dad.", author: "Wei (Dad)" },
      { id: "n2", scope: "trip", text: "Meet at hotel lobby at 8:30 each morning.", author: "Lin (Mum)" },
    ],
    bookings: seedBookings,
    tasks: seedTasks,
    packing: seedPacking,
    activeTravellerId: "dad",
    currentDay: 3,
    replanLog: [],
    cachedAt: null,
  };
}
