/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as ConsensusRouteImport } from './routes/consensus'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GettingReadyRouteImport } from './routes/getting-ready'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PrintRouteImport } from './routes/print'
import { Route as ReplanRouteImport } from './routes/replan'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as FitAttractionIdRouteImport } from './routes/fit.$attractionId'
import { Route as OpsConsoleRouteImport } from './routes/ops.console'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsensusRoute = ConsensusRouteImport.update({
  id: '/consensus',
  path: '/consensus',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingReadyRoute = GettingReadyRouteImport.update({
  id: '/getting-ready',
  path: '/getting-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplanRoute = ReplanRouteImport.update({
  id: '/replan',
  path: '/replan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const FitAttractionIdRoute = FitAttractionIdRouteImport.update({
  id: '/fit/$attractionId',
  path: '/fit/$attractionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsConsoleRoute = OpsConsoleRouteImport.update({
  id: '/ops/console',
  path: '/ops/console',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/changes': typeof ChangesRoute
  '/consensus': typeof ConsensusRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/fairness': typeof FairnessRoute
  '/family': typeof FamilyRoute
  '/getting-ready': typeof GettingReadyRoute
  '/invite': typeof InviteRoute
  '/itinerary': typeof ItineraryRoute
  '/join': typeof JoinRoute
  '/preferences': typeof PreferencesRoute
  '/print': typeof PrintRoute
  '/replan': typeof ReplanRoute
  '/review': typeof ReviewRoute
  '/roles': typeof RolesRoute
  '/sponsor': typeof SponsorRoute
  '/today': typeof TodayRoute
  '/trips': typeof TripsRoute
  '/updates': typeof UpdatesRoute
  '/fit/$attractionId': typeof FitAttractionIdRoute
  '/ops/console': typeof OpsConsoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/changes': typeof ChangesRoute
  '/consensus': typeof ConsensusRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/fairness': typeof FairnessRoute
  '/family': typeof FamilyRoute
  '/getting-ready': typeof GettingReadyRoute
  '/invite': typeof InviteRoute
  '/itinerary': typeof ItineraryRoute
  '/join': typeof JoinRoute
  '/preferences': typeof PreferencesRoute
  '/print': typeof PrintRoute
  '/replan': typeof ReplanRoute
  '/review': typeof ReviewRoute
  '/roles': typeof RolesRoute
  '/sponsor': typeof SponsorRoute
  '/today': typeof TodayRoute
  '/trips': typeof TripsRoute
  '/updates': typeof UpdatesRoute
  '/fit/$attractionId': typeof FitAttractionIdRoute
  '/ops/console': typeof OpsConsoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/changes': typeof ChangesRoute
  '/consensus': typeof ConsensusRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/fairness': typeof FairnessRoute
  '/family': typeof FamilyRoute
  '/getting-ready': typeof GettingReadyRoute
  '/invite': typeof InviteRoute
  '/itinerary': typeof ItineraryRoute
  '/join': typeof JoinRoute
  '/preferences': typeof PreferencesRoute
  '/print': typeof PrintRoute
  '/replan': typeof ReplanRoute
  '/review': typeof ReviewRoute
  '/roles': typeof RolesRoute
  '/sponsor': typeof SponsorRoute
  '/today': typeof TodayRoute
  '/trips': typeof TripsRoute
  '/updates': typeof UpdatesRoute
  '/fit/$attractionId': typeof FitAttractionIdRoute
  '/ops/console': typeof OpsConsoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/bookings'
    | '/changes'
    | '/consensus'
    | '/create'
    | '/discover'
    | '/fairness'
    | '/family'
    | '/getting-ready'
    | '/invite'
    | '/itinerary'
    | '/join'
    | '/preferences'
    | '/print'
    | '/replan'
    | '/review'
    | '/roles'
    | '/sponsor'
    | '/today'
    | '/trips'
    | '/updates'
    | '/fit/$attractionId'
    | '/ops/console'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/bookings'
    | '/changes'
    | '/consensus'
    | '/create'
    | '/discover'
    | '/fairness'
    | '/family'
    | '/getting-ready'
    | '/invite'
    | '/itinerary'
    | '/join'
    | '/preferences'
    | '/print'
    | '/replan'
    | '/review'
    | '/roles'
    | '/sponsor'
    | '/today'
    | '/trips'
    | '/updates'
    | '/fit/$attractionId'
    | '/ops/console'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/bookings'
    | '/changes'
    | '/consensus'
    | '/create'
    | '/discover'
    | '/fairness'
    | '/family'
    | '/getting-ready'
    | '/invite'
    | '/itinerary'
    | '/join'
    | '/preferences'
    | '/print'
    | '/replan'
    | '/review'
    | '/roles'
    | '/sponsor'
    | '/today'
    | '/trips'
    | '/updates'
    | '/fit/$attractionId'
    | '/ops/console'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  ChangesRoute: typeof ChangesRoute
  ConsensusRoute: typeof ConsensusRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  FairnessRoute: typeof FairnessRoute
  FamilyRoute: typeof FamilyRoute
  GettingReadyRoute: typeof GettingReadyRoute
  InviteRoute: typeof InviteRoute
  ItineraryRoute: typeof ItineraryRoute
  JoinRoute: typeof JoinRoute
  PreferencesRoute: typeof PreferencesRoute
  PrintRoute: typeof PrintRoute
  ReplanRoute: typeof ReplanRoute
  ReviewRoute: typeof ReviewRoute
  RolesRoute: typeof RolesRoute
  SponsorRoute: typeof SponsorRoute
  TodayRoute: typeof TodayRoute
  TripsRoute: typeof TripsRoute
  UpdatesRoute: typeof UpdatesRoute
  FitAttractionIdRoute: typeof FitAttractionIdRoute
  OpsConsoleRoute: typeof OpsConsoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consensus': {
      id: '/consensus'
      path: '/consensus'
      fullPath: '/consensus'
      preLoaderRoute: typeof ConsensusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-ready': {
      id: '/getting-ready'
      path: '/getting-ready'
      fullPath: '/getting-ready'
      preLoaderRoute: typeof GettingReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replan': {
      id: '/replan'
      path: '/replan'
      fullPath: '/replan'
      preLoaderRoute: typeof ReplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fit/$attractionId': {
      id: '/fit/$attractionId'
      path: '/fit/$attractionId'
      fullPath: '/fit/$attractionId'
      preLoaderRoute: typeof FitAttractionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/console': {
      id: '/ops/console'
      path: '/ops/console'
      fullPath: '/ops/console'
      preLoaderRoute: typeof OpsConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  ChangesRoute: ChangesRoute,
  ConsensusRoute: ConsensusRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  FairnessRoute: FairnessRoute,
  FamilyRoute: FamilyRoute,
  GettingReadyRoute: GettingReadyRoute,
  InviteRoute: InviteRoute,
  ItineraryRoute: ItineraryRoute,
  JoinRoute: JoinRoute,
  PreferencesRoute: PreferencesRoute,
  PrintRoute: PrintRoute,
  ReplanRoute: ReplanRoute,
  ReviewRoute: ReviewRoute,
  RolesRoute: RolesRoute,
  SponsorRoute: SponsorRoute,
  TodayRoute: TodayRoute,
  TripsRoute: TripsRoute,
  UpdatesRoute: UpdatesRoute,
  FitAttractionIdRoute: FitAttractionIdRoute,
  OpsConsoleRoute: OpsConsoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
